routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/crm', 'CrmController@index')->name('crm');
Route::get('/home', 'HomeController@index');


Route::middleware('role:admin')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('roles', 'RoleController');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/usuario-role/{idUsuario}', 'UsuarioRoleController@buscaRolesUsuario');
    Route::put('/usuario-role/{idUsuario}', 'UsuarioRoleController@buscaRolesUsuario');
    
});


Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('empresa', 'EmpresaController');
});

Route::middleware('auth')->prefix('user')->namespace('User')->group(function(){
    Route::resource('estoque', 'EstoqueController');
    Route::resource('chip', 'ChipController');
    Route::resource('equipamento', 'EquipamentoController');
    Route::resource('fornecedor', 'FornecedorController');
    Route::get('busca-chip/{id}', 'KitController@buscaChip');
    Route::get('busca-equip/{id}', 'KitController@buscaEquip');
    Route::resource('kit', 'KitController');
    Route::resource('produto', 'ProdutoController');
    Route::resource('movimento', 'MovimentoController');
    Route::get('limpa/{key}', 'MovimentoController@clearSessionKey');
});

app/Usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuario extends Model
{
    //
}

app/Http/Controllers/Admin/UsuarioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Busca do banco todos os usuários para carregar na view
        $usuarios = User::get();

        // Busca na sessão os dados do usuario logado
        $usuarioLogado = auth()->user();
        
        // Funcao da biblioteca spatie/laravel que busca as roles de um usuario
        $rolesUsuario = $usuarioLogado->roles;

        // Funcao da biblioteca spatie/laravel que busca as permissoes de um usuario
        $permissionsUsuario = $usuarioLogado->permissions;

        // Funcao da biblioteca spatie/laravel que busca as permissoes de um usuario
        $roles = Role::get();

        // Variável responsável por passar ao breadcrumb(lista de migalhas)
        // o caminho percorrido
        $listaMigalhas = json_encode([
            ['titulo' => 'Home', 'url' => '/'],
            ['titulo' => 'Usuarios', 'url' => '']
        ]);



        return view('admin.usuario.index', compact('usuarios', 'listaMigalhas', 'rolesUsuario', 'permissionsUsuario', 'roles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Pega todos os dados da requisao
        $data = $request->all();

        // Busca usuario para modificar
        $usuario = User::find($id);

        // Verifica se possui a variavel com as roles
        if(isset($data['roles'])) {
            // Armazena as roles em uma variável
            $roles = $data['roles'];
            

            // Modifica as roles do usuario, funcao do spatie que remove todas as roles
            // e atualiza com as roles do array passado como parametro.
            $usuario->syncRoles($roles);

        }
        
        // Atualiza o usuario com as informações 
        $usuario->update($data);

        // Busca todos os usuarios no banco
        $listaUsuarios = User::all();

        // Retorna os usuarios  
        return $listaUsuarios;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Busca o usuario a ser excluido
        $usuario = User::find($id);

        // Deleta o usuario

        $usuario->delete();

        // Retorna todos os usuarios
        return User::all();
    }
}

resources/views/admin/usuario/index.blade.php
@extends('layouts.app')

@section('content')
<div>
    <caminho-migalhas v-bind:list="{{$listaMigalhas}}"></caminho-migalhas>
    <div class="row ml-3 mr-3">
        <div class="col-md-12">
            @if($errors->all())
                <div class="alert alert-danger alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                    @foreach( $errors->all() as $key => $value)
                    <li><strong>{{$value}}</strong> </li>
                    @endforeach
                </div>
            @endif

        </div>
    </div>
    <div class="row mr-3 ml-3">
        <div class="col-md-8">
            <painel-geral nome="Listagem de Usuarios">
                <tabela-usuario id-usuario="{{auth()->user()->id}}" url-roles="{{ url('admin/usuario-role/')}}" v-bind:itens="{{$usuarios}}"></tabela-usuario>
            </painel-geral>
        </div>
        <div class="col-md-4">
            <div class="row">
                    <formulario-usuario  
                    url="{{ route('usuario.store')}}" 
                    v-bind:roles="{{$roles}}" 
                    v-bind:roles-usuario="{{$rolesUsuario}}"  
                    token="{{csrf_token()}}"></formulario-usuario>
                
            </div>
            <div class="row pt-2">
                    <funcoes-usuario  
                    url-roles="{{ url('admin/usuario-role/')}}"
                    url-user="{{ route('usuario.store') }}"
                    v-bind:roles="{{$roles}}" 
                    v-bind:roles-usuario="{{$rolesUsuario}}" 
                    token="{{csrf_token()}}">
                    </funcoes-usuario>  
                
            </div>
            
        </div>
        
    </div>
</div>
@endsection