routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/crm', 'CrmController@index')->name('crm');
Route::get('/home', 'HomeController@index');


Route::middleware('role:admin')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('roles', 'RoleController');
    Route::resource('usuario', 'UsuarioController');
    Route::get('/usuario-role/{idUsuario}', 'UsuarioRoleController@buscaRolesUsuario');
    Route::put('/usuario-role/{idUsuario}', 'UsuarioRoleController@buscaRolesUsuario');
    
});


Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('empresa', 'EmpresaController');
});

Route::middleware('auth')->prefix('user')->namespace('User')->group(function(){
    Route::resource('estoque', 'EstoqueController');
    Route::resource('chip', 'ChipController');
    Route::resource('equipamento', 'EquipamentoController');
    Route::resource('fornecedor', 'FornecedorController');
    Route::get('busca-chip/{id}', 'KitController@buscaChip');
    Route::get('busca-equip/{id}', 'KitController@buscaEquip');
    Route::resource('kit', 'KitController');
    Route::resource('produto', 'ProdutoController');
    Route::resource('movimento', 'MovimentoController');
    Route::get('limpa/{key}', 'MovimentoController@clearSessionKey');
});

app/Empresa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    protected $fillable = [
        'emp_razao_social', 'emp_nome_fantasia', 'emp_cnpj', 'emp_tel', 'emp_contato', 'emp_email', 
        'emp_website', 'emp_tel_sec', 'emp_fax', 'emp_rua', 'emp_numero', 'emp_complemento', 'emp_bairro',
        'emp_estado', 'emp_cidade', 'emp_cep',
    ];
}

app/Http/Controllers/Admin/EmpresaController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Empresa;
use App\Endereco;

class EmpresaController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Array que fornece informações de opções do megamenu

        $listaOpcoesEmpresa = json_encode([
            ["titulo"=>"Contas", 
            "acoes"=>[["icone"=>"fa fa-plus", "texto"=>"Incluir", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Exibir Todas", "url"=>"/show"],]
            ],
            ["titulo"=>"Contas a receber", 
            "acoes"=>[["icone"=>"fa fa-plus", "texto"=>"Incluir", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Exibir Todas", "url"=>"/show"],
                ["icone"=>"fa fa-plus", "texto"=>"Deletar", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Ação Todas", "url"=>"/show"],
                ["icone"=>"fa fa-plus", "texto"=>"Ação Qualquer", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Exibir", "url"=>"/show"],]
            ],
            ["titulo"=>"Contas", 
            "acoes"=>[["icone"=>"fa fa-plus", "texto"=>"Incluir", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Exibir Todas", "url"=>"/show"]]
            ],
            ["titulo"=>"Contas", 
            "acoes"=>[["icone"=>"fa fa-plus", "texto"=>"Incluir", "url"=>"/add"],
                ["icone"=>"fa fa-list-ul", "texto"=>"Exibir Todas", "url"=>"/show"]]
            ]
        ]);


        // Array que fornece informações para geração do Breadcrumb
        $listaMigalhas = json_encode([
            ['titulo' => 'Home', 'url' => '/'],
            ['titulo' => 'Dados da Empresa', 'url' => '']
        ]);

        $dadosEmpresa = json_encode(DB::table('empresas')->first());

        return view('admin/empresa/home',compact('listaMigalhas', 'listaOpcoesEmpresa', 'dadosEmpresa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();

        Empresa::create($data);
        dd($data);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/empresa/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <nav aria-label="breadcrumb">
                <caminho-migalhas v-bind:list="{{$listaMigalhas}}"></caminho-migalhas>   
            </nav>
            <div class="card">
                <div class="card-header">Dados da empresa </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form id="empresaForm" action="{{ route('empresa.store')}}" method="post" enctype="" token="{{ csrf_token() }}">
                        <principal-empresa dados="{{ $dadosEmpresa }}"></principal-empresa>
                        {{ csrf_field() }}

                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Endereço</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Telefones e E-mail</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Mapa</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <endereco-empresa dados="{{ $dadosEmpresa }}"></endereco-empresa>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <telefone-empresa></telefone-empresa>
                            </div>
                            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-auto">
                                <button type="submit" form="empresaForm" class="btn btn-success">Salvar Dados</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection